version: "3"

services:
  # PiHole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${PI_TZ}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  #  Home Assistant
  home:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./home-assistant:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: ${PI_TZ}
    ports:
      - "8123:8123"
